name: CJFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 3.6
description: Plugin for the CJFreedom server.
authors: [Madgeek1450, DarthSalamon, Wild1145]

# plugin.yml is no longer used to define commands.
