name: TotalFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 2.18
description: Plugin for the Total Freedom server.
authors: [StevenLawson / Madgeek1450, JeromSar / DarthSalamon,  RyanWild / Wild1145, DanJones / HeXeRei452]

# plugin.yml is no longer used to define MOST commands.
# /opme /creative and /survival will need to be re-added due to MCMyadmin using these commands!
