name: CJFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 2.25
description: Plugin for the Total Freedom server.
authors: [StevenLawson / Madgeek1450, JeromSar / DarthSalamon, RyanWild / Wild1145]

# plugin.yml is no longer used to define commands.
