name: CJFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 3.1
description: Plugin for the Total Freedom server.
authors: [Madgeek1450, DarthSalamon, Wild1145]

# plugin.yml is no longer used to define commands.
